# Generated by Django 5.2 on 2025-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('product_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
